// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "FeaturesIconCards" section.

import React from 'react';
import FeaturesIconCards from "@/components/sections/features/FeaturesIconCards";

export default function FeaturesIconCardsSection(): React.JSX.Element {
  return (
    <div data-webild-section="FeaturesIconCards"><FeaturesIconCards
            tag="WHY DIACOS RESTAURANT SUPPLY GROUP"
            title="Why Commercial Kitchens Trust Diacos Restaurant Supply"
            description="We keep your food service business running smoothly with reliable wholesale distribution and trusted culinary ingredients."
            primaryButton={{"text":"View Catalog","href":"/catalog"}}
            secondaryButton={{"text":"Contact Sales","href":"/contact"}}
            features={[{"icon":"Truck","title":"Reliable Supply","description":"Consistent stock and fast fulfillment so your kitchen never runs short."},{"icon":"ShieldCheck","title":"Trusted Brands","description":"We only carry ingredients from suppliers the industry already trusts."},{"icon":"BadgePercent","title":"Wholesale Pricing","description":"Competitive pricing built for restaurants and bakeries ordering at volume."}]}
            textAnimation="slide-up"
          /></div>
  );
}
