// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "SocialProofMarquee" section.

import React from 'react';
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";

export default function SocialProofMarqueeSection(): React.JSX.Element {
  return (
    <div data-webild-section="SocialProofMarquee"><section aria-label="Social proof section" className="py-20"><div className="flex flex-col gap-8 md:gap-10"><div className="flex flex-col items-center gap-2 w-content-width mx-auto"><div className="px-3 py-1 mb-1 text-sm card rounded w-fit"><p>Trusted Suppliers</p></div><TextAnimation text="Industry Brands Commercial Kitchens Count On" variant="slide-up" gradientText={true} tag="h2" className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance" /><TextAnimation text="We partner with top culinary suppliers to bring commercial kitchens premium flours, chocolates, fillings, and dairy with guaranteed fast fulfillment." variant="slide-up" gradientText={false} tag="p" className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance" /><div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3"><Button text="View Catalog" href="/catalog" variant="primary" /><Button text="Contact Sales" href="/contact" variant="secondary" animationDelay={0.1} /></div></div><ScrollReveal variant="slide-up" className="w-content-width mx-auto overflow-hidden mask-fade-x"><div className="flex w-max animate-marquee-horizontal" style={{"animationDuration":"45s"}}><div key={0} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Pillsbury (Premium Bakery Flours & Mixes)</span></div>
    <div key={1} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Philadelphia (Cream Cheese & Dairy Specialties)</span></div>
    <div key={2} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Puratos (Bakery, Patisserie & Chocolate)</span></div>
    <div key={3} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Henry & Henry (Fruit Fillings, Icings & Glazes)</span></div>
    <div key={4} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Pillsbury (Premium Bakery Flours & Mixes)</span></div>
    <div key={5} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Philadelphia (Cream Cheese & Dairy Specialties)</span></div>
    <div key={6} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Puratos (Bakery, Patisserie & Chocolate)</span></div>
    <div key={7} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Henry & Henry (Fruit Fillings, Icings & Glazes)</span></div>
    <div key={8} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Pillsbury (Premium Bakery Flours & Mixes)</span></div>
    <div key={9} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Philadelphia (Cream Cheese & Dairy Specialties)</span></div>
    <div key={10} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Puratos (Bakery, Patisserie & Chocolate)</span></div>
    <div key={11} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Henry & Henry (Fruit Fillings, Icings & Glazes)</span></div>
    <div key={12} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Pillsbury (Premium Bakery Flours & Mixes)</span></div>
    <div key={13} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Philadelphia (Cream Cheese & Dairy Specialties)</span></div>
    <div key={14} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Puratos (Bakery, Patisserie & Chocolate)</span></div>
    <div key={15} className="shrink-0 mx-3 px-5 py-3 rounded card"><span className="text-2xl font-semibold whitespace-nowrap opacity-75">Henry & Henry (Fruit Fillings, Icings & Glazes)</span></div></div></ScrollReveal></div></section></div>
  );
}
