// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, CheckCircle, Sparkles } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Wholesale & Culinary Quality"
          title="Premium Ingredients for Bakery Professionals"
          description="We partner with trusted names in the industry to bring commercial kitchens dependable flours, dairy, fillings, and chocolate at competitive wholesale pricing."
          items={[
            {
              icon: CheckCircle,
              title: "Reliable Supply",
              description: "Consistent stock and fast fulfillment so your kitchen never runs short.",
            },
            {
              icon: Sparkles,
              title: "Trusted Brands",
              description: "Top-tier ingredients from suppliers the food service industry trusts.",
            },
            {
              icon: Award,
              title: "Wholesale Pricing",
              description: "Competitive pricing built for volume bakery and restaurant orders.",
            },
          ]}
          imageSrc="https://picsum.photos/seed/1533423214/1200/800"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
