// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, CheckCircle, Sparkles } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Artisanal Integrity"
          title="Crafted to Last"
          description="Every item in our collection is hand-selected from artisans who value quality over volume. We bridge the gap between tradition and modern necessity."
          items={[
            {
              icon: CheckCircle,
              title: "Handcrafted Excellence",
              description: "Strict quality control on every batch.",
            },
            {
              icon: Sparkles,
              title: "Curated Design",
              description: "Pieces that tell a unique story.",
            },
            {
              icon: Award,
              title: "Legacy Quality",
              description: "Built to endure decades of use.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/laptop-skincare-supplies_23-2147711561.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
