// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "catalog" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CatalogSection(): React.JSX.Element {
  return (
    <div id="catalog" data-section="catalog">
        <SectionErrorBoundary name="catalog">
              <FeaturesImageBento
          tag="Collections"
          title="Shop the Collection"
          description="Explore our curated categories, each representing a facet of refined modern living."
          items={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842903795-faox9v3u.png",
              title: "",
              description: "",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842862033-pkvsgoc6.png",
              title: "",
              description: "",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842891176-3ynwbynj.png",
              title: "",
              description: "",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842834929-13gz2gmx.png",
              title: "",
              description: "",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842939359-17bmy712.png",
              title: "",
              description: "",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842923464-azxbnfn7.png",
              title: "",
              description: "",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842964795-f4z1ntv4.png",
              title: "",
              description: "",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
