/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const items = [
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842903795-faox9v3u.png",
    title: "",
    description: ""
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842862033-pkvsgoc6.png",
    title: "",
    description: ""
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842891176-3ynwbynj.png",
    title: "",
    description: ""
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842834929-13gz2gmx.png",
    title: "",
    description: ""
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842939359-17bmy712.png",
    title: "",
    description: ""
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842923464-azxbnfn7.png",
    title: "",
    description: ""
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786842964795-f4z1ntv4.png",
    title: "",
    description: ""
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesImageBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: [FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const CatalogInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-2",
    "md:col-span-2",
    "md:col-span-2",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0.2,
  ];

  return (
    <section aria-label="Features image bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Collections"}</p>
          </div>

          <TextAnimation
            text={"Shop the Collection"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Explore our curated categories, each representing a facet of refined modern living."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div id="grid" className="w-content-width mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
          <div className="product-card card p-5 rounded-lg flex flex-col gap-2">
            <div className="category text-xs font-semibold uppercase tracking-wider text-accent">Pies</div>
            <h3 className="text-base font-semibold text-foreground">10&quot; Apple Pies Gardner</h3>
            <div className="meta text-xs text-accent">SKU PIES-0006 · GARDNER · unit</div>
            <div className="price text-lg font-bold text-foreground mt-auto">$64.33</div>
          </div>
          <div className="product-card card p-5 rounded-lg flex flex-col gap-2">
            <div className="category text-xs font-semibold uppercase tracking-wider text-accent">Pies</div>
            <h3 className="text-base font-semibold text-foreground">10&quot; Blueberry Pie Gardner</h3>
            <div className="meta text-xs text-accent">SKU PIES-0008 · unit</div>
            <div className="price text-lg font-bold text-foreground mt-auto">$76.02</div>
          </div>
          <div className="product-card card p-5 rounded-lg flex flex-col gap-2">
            <div className="category text-xs font-semibold uppercase tracking-wider text-accent">Pies</div>
            <h3 className="text-base font-semibold text-foreground">10&quot; Pumpkin Pie - Gardner</h3>
            <div className="meta text-xs text-accent">SKU PIES-0012 · unit</div>
            <div className="price text-lg font-bold text-foreground mt-auto">$60.13</div>
          </div>
          <div className="product-card card p-5 rounded-lg flex flex-col gap-2">
            <div className="category text-xs font-semibold uppercase tracking-wider text-accent">Pies</div>
            <h3 className="text-base font-semibold text-foreground">9&quot; Gardner Cherry Pie</h3>
            <div className="meta text-xs text-accent">SKU PIES-0013 · GARDNER · unit</div>
            <div className="price text-lg font-bold text-foreground mt-auto">$82.53</div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default function CatalogSection() {
  return (
    <div data-webild-section="catalog" data-section="catalog" id="catalog">
      <CatalogInline />
    </div>
  );
}
