// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get in touch"
          text="Ready to bring artisanal quality to your space? Let's connect."
          primaryButton={{
            text: "Email Us",
            href: "mailto:hello@diacos.com",
          }}
          secondaryButton={{
            text: "Call Support",
            href: "tel:+1234567890",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
