// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Support"
          title="Frequently Asked"
          description="Everything you need to know about our sourcing."
          items={[
            {
              question: "Are products artisanal?",
              answer: "Yes, every single piece is hand-finished.",
            },
            {
              question: "What is the return policy?",
              answer: "We offer returns within 30 days of delivery.",
            },
            {
              question: "Can I request custom items?",
              answer: "Certain artisans accept custom commissions.",
            },
            {
              question: "Where do you ship?",
              answer: "We ship globally to over 50 countries.",
            },
            {
              question: "Are materials sustainable?",
              answer: "We prioritize eco-friendly and reclaimed materials.",
            },
            {
              question: "What is the lead time?",
              answer: "In-stock items ship within 48 hours.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
