/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import TiltedCarousel from "@/components/ui/TiltedCarousel";

const primaryButton = {
  text: "View Catalog",
  href: "#catalog"
};
const secondaryButton = {
  text: "Our Story",
  href: "#about"
};
const items = [
  {
    imageSrc: "https://picsum.photos/seed/679327160/1200/800"
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786841547164-qbipz599.png"
  },
  {
    imageSrc: "https://picsum.photos/seed/1301325396/1200/800"
  },
  {
    imageSrc: "https://storage.googleapis.com/webild/users/user_3Hy0hX45s3VxHQbTscSlYSkC3nn/uploaded-1786841361429-osvmzh9x.png"
  },
  {
    imageSrc: "https://picsum.photos/seed/910576897/1200/800"
  },
  {
    imageSrc: "https://picsum.photos/seed/1607010896/1200/800"
  }
];

type HeroBillboardTiltedCarouselProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  items: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const HomeInline = () => {
  return (
    <section
      aria-label="Hero section"
      className="relative flex flex-col items-center justify-center gap-8 md:gap-10 w-full min-h-svh pt-25 pb-20 md:pt-30"
    >
      <HeroBackgroundSlot />
      <div className="flex flex-col items-center gap-3 w-content-width mx-auto text-center">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Wholesale · Restaurant & Bakery Supply"}</p>
        </div>

        <TextAnimation
          text={"Everything Your Kitchen Needs, Ready to Order"}
          variant={"slide-up"}
          gradientText={true}
          tag="h1"
          className="md:max-w-8/10 text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Premium flours, dairy, fillings, and chocolate for restaurants and bakeries that won't compromise on quality."}
          variant={"slide-up"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-balance"
        />

        <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
          <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>
          <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary"animationDelay={0.1} />
        </div>
      </div>

      <TiltedCarousel items={items} />
    </section>
  );
};

export default function HomeSection() {
  return (
    <div data-webild-section="home" data-section="home" id="home">
      <HomeInline />
    </div>
  );
}
