/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import TiltedCarousel from "@/components/ui/TiltedCarousel";

const primaryButton = {
  text: "View Catalog",
  href: "#catalog"
};
const secondaryButton = {
  text: "Our Story",
  href: "#about"
};
const items = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/full-shot-woman-working-with-flowers_23-2149591604.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/vintage-desk-concept_23-2147791084.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-arrangement-modern-vases_23-2149646558.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/grunge-style-metal-with-different-metallic-textures_1048-13647.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-arrangement-modern-vases_23-2149646508.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/cozy-autumn-composition-with-decorative-details-candles_169016-23374.jpg"
  }
];

type HeroBillboardTiltedCarouselProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  items: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const HomeInline = () => {
  return (
    <section
      aria-label="Hero section"
      className="relative flex flex-col items-center justify-center gap-8 md:gap-10 w-full min-h-svh pt-25 pb-20 md:pt-30"
    >
      <HeroBackgroundSlot />
      <div className="flex flex-col items-center gap-3 w-content-width mx-auto text-center">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Since 1984"}</p>
        </div>

        <TextAnimation
          text={"Exquisite Supplies for Modern Life"}
          variant={"slide-up"}
          gradientText={true}
          tag="h1"
          className="md:max-w-8/10 text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Discover a curated selection of artisanal goods, crafted with precision and passion for your home and lifestyle."}
          variant={"slide-up"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-balance"
        />

        <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
          <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>
          <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary"animationDelay={0.1} />
        </div>
      </div>

      <TiltedCarousel items={items} />
    </section>
  );
};

export default function HomeSection() {
  return (
    <div data-webild-section="home" data-section="home" id="home">
      <HomeInline />
    </div>
  );
}
