// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "home" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HomeSection(): React.JSX.Element {
  return (
    <div id="home" data-section="home">
        <SectionErrorBoundary name="home">
              <HeroBillboardTiltedCarousel
          tag="Since 1984"
          title="Exquisite Supplies for Modern Life"
          description="Discover a curated selection of artisanal goods, crafted with precision and passion for your home and lifestyle."
          primaryButton={{
            text: "View Catalog",
            href: "#catalog",
          }}
          secondaryButton={{
            text: "Our Story",
            href: "#about",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-woman-working-with-flowers_23-2149591604.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/vintage-desk-concept_23-2147791084.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-arrangement-modern-vases_23-2149646558.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/grunge-style-metal-with-different-metallic-textures_1048-13647.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-arrangement-modern-vases_23-2149646508.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/cozy-autumn-composition-with-decorative-details-candles_169016-23374.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
