// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="The Impact"
          title="Measured by Quality"
          description="Numbers reflect our commitment to excellence."
          metrics={[
            {
              value: "12k+",
              title: "Items Curated",
              features: [
                "Validated origin",
                "Sustainable sourcing",
                "Quality inspected",
              ],
            },
            {
              value: "450+",
              title: "Partner Artisans",
              features: [
                "Fair trade practices",
                "Long-term relationships",
                "Direct support",
              ],
            },
            {
              value: "98%",
              title: "Satisfaction Rate",
              features: [
                "Lifetime support",
                "Easy returns",
                "Quality assured",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
