// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { Check } from "lucide-react";

const valueCards = [
  {
    title: "Wide Selection",
    description: "Flours, dairy, fillings, glazes, and chocolate from trusted industry brands.",
    bullets: [
      "Bulk flours, sugars & specialty grains",
      "Real dairy, chocolates & pastry fillings",
      "Trusted commercial culinary brands"
    ]
  },
  {
    title: "Reliable Fulfillment",
    description: "Consistent stock and fast delivery for restaurants and bakeries.",
    bullets: [
      "Consistent inventory availability",
      "Fast & scheduled kitchen deliveries",
      "Careful handling of temperature-sensitive goods"
    ]
  },
  {
    title: "Wholesale Pricing",
    description: "Competitive pricing built for kitchens ordering at volume.",
    bullets: [
      "Volume-based wholesale discounts",
      "Transparent business pricing",
      "Direct commercial account support"
    ]
  }
];

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-webild-section="metrics" data-section="metrics" className="py-16 md:py-24 bg-background">
      <div className="w-content-width mx-auto flex flex-col gap-12">
        <ScrollReveal variant="slide-up">
          <div className="flex flex-col items-center text-center gap-3">
            <div className="px-3 py-1 text-sm card rounded w-fit">
              <p className="text-accent font-medium">Wholesale Quality</p>
            </div>
            <TextAnimation
              text="Built for Kitchen Quality & Efficiency"
              variant="slide-up"
              gradientText={false}
              tag="h2"
              className="text-4xl md:text-5xl font-bold text-foreground text-balance"
            />
            <p className="text-lg md:text-xl text-accent max-w-2xl text-balance">
              Every order is backed by industry expertise, premium sourcing, and dependable wholesale service.
            </p>
          </div>
        </ScrollReveal>

        <ScrollReveal variant="slide-up" delay={0.2}>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8">
            {valueCards.map((card, idx) => (
              <div key={idx} className="card p-6 md:p-8 rounded-2xl flex flex-col justify-between gap-6 shadow-sm border border-border/40">
                <div className="flex flex-col gap-3">
                  <h3 className="text-2xl font-bold text-foreground">{card.title}</h3>
                  <p className="text-foreground/90 font-medium leading-relaxed">{card.description}</p>
                </div>
                <ul className="flex flex-col gap-2.5 pt-4 border-t border-border/30">
                  {card.bullets.map((bullet, bIdx) => (
                    <li key={bIdx} className="flex items-start gap-2.5 text-sm text-accent">
                      <Check className="w-4 h-4 text-primary-cta shrink-0 mt-0.5" />
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </ScrollReveal>
      </div>
    </div>
  );
}
