// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialSection(): React.JSX.Element {
  return (
    <div id="social" data-section="social">
        <SectionErrorBoundary name="social">
              <SocialProofMarquee
          tag="In Partnership"
          title="Selected Partners"
          description="Collaborating with visionaries globally."
          names={[
            "Studio Co",
            "Modern Home",
            "Design Hub",
            "Artisan Lab",
            "Urban Living",
            "Decor Daily",
            "Refined Life",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
