// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialOverlayCards from '@/components/sections/testimonial/TestimonialOverlayCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialOverlayCards
          tag="Kind Words"
          title="Stories from Our Community"
          description="Trusted by discerning individuals worldwide."
          testimonials={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/attractive-casully-dressed-young-latin-woman-sitting-windowsill-kitchen-holding-cell-phone-checking-newsfeed-via-social-network-typing-text-message-having-rest-technology-communication_344912-2094.jpg",
              name: "Elena Ross",
              role: "Designer",
              company: "Studio N",
              rating: 5,
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/influencer-holding-coffee-cup-recording-podcast-home-studio_482257-7797.jpg",
              name: "Mark Vane",
              role: "Architect",
              company: "Vane Associates",
              rating: 5,
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/middle-aged-bearded-man-with-cheerful-expression-pointing-thumb-his-girlfriend-sunglasses-while-telling-jokes_273609-6608.jpg",
              name: "Sarah Lee",
              role: "Collector",
              company: "Independent",
              rating: 5,
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-young-woman-with-eyeglasses-holding-shopping-bags_23-2147823601.jpg",
              name: "James K.",
              role: "Chef",
              company: "Bistro 4",
              rating: 5,
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/young-people-modeling-photoshoot_273609-12739.jpg",
              name: "Chloe B.",
              role: "Stylist",
              company: "Mode",
              rating: 5,
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
