// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";

const supplierLogos = [
  "Pillsbury",
  "Philadelphia",
  "Puratos",
  "Henry & Henry"
];

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-webild-section="testimonials" data-section="testimonials" className="bg-background">
      <div className="w-content-width mx-auto flex flex-col items-center text-center gap-8">
        <ScrollReveal variant="slide-up">
          <div className="px-3 py-1 text-sm card rounded w-fit mx-auto mb-3">
            <p className="text-accent font-medium">Wholesale Quality</p>
          </div>
          <TextAnimation
            text="Trusted by Restaurants and Bakeries"
            variant="slide-up"
            gradientText={false}
            tag="h2"
            className="text-4xl md:text-5xl font-bold text-foreground text-balance"
          />
          <p className="mt-4 text-lg md:text-xl text-accent max-w-content-width mx-auto text-balance">
            We supply kitchens that won't compromise on quality — from independent bakeries to full-service restaurants.
          </p>
        </ScrollReveal>

        <ScrollReveal variant="fade-blur" delay={0.2}>
          <div className="flex flex-wrap items-center justify-center gap-4 md:gap-8 mt-4">
            {supplierLogos.map((brand, idx) => (
              <div
                key={idx}
                className="card px-8 py-5 rounded-xl flex items-center justify-center font-bold text-xl md:text-2xl text-foreground tracking-wide shadow-sm"
              >
                {brand}
              </div>
            ))}
          </div>
        </ScrollReveal>
      </div>
    </div>
  );
}